version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/zuchzub/Go"


[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true
